# Generated by Django 4.2.1 on 2023-05-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name': 'Constituency', 'verbose_name_plural': 'Constituencies'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'verbose_name': 'Disability', 'verbose_name_plural': 'Disabilities'},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'verbose_name': 'MaritalStatus', 'verbose_name_plural': 'MaritalStatus'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='subounty',
            options={'verbose_name': 'Subounty', 'verbose_name_plural': 'Subounties'},
        ),
    ]
