# Generated by Django 4.2.1 on 2023-06-18 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('advert_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('post_vacancy', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_post', models.IntegerField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('duties_responsibilities', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='Kes', max_length=10)),
                ('basic_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('house_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('commuter_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_allowance', models.CharField(blank=True, default='As provided in TSC Secretariat', max_length=100, null=True)),
                ('medical_scheme', models.CharField(blank=True, default='As provided in the TSC Secretariat Medical Scheme', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.category')),
                ('category_target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.targetgroup')),
                ('is_closed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.status')),
                ('pay_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.paytype')),
                ('term_of_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.termofservice')),
            ],
        ),
    ]
