# Generated by Django 4.2.1 on 2023-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantprofiles', '0002_alter_academicqualification_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevantcourse',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
